ci:
  skip:
    - pylint
    - poetry-check
    - poetry-lock
    - poetry-export
    - check-yaml

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: '1.6.1'
    hooks:
      - id: poetry-check
      - id: poetry-lock
        args:
          - --no-update
      - id: poetry-export
        name: export requirements.txt
        args: [ "--format=requirements.txt", "--without-hashes", "-o", "requirements.txt" ]
      - id: poetry-export
        name: export requirements-dev.txt
        args: [ "--format=requirements.txt", "--without-hashes", "-o", "requirements-dev.txt", "--only", "dev" ]
      - id: poetry-export
        name: export requirements-docs.txt
        args: [ "--format=requirements.txt", "--without-hashes", "-o", "requirements-docs.txt", "--only", "docs" ]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.4.0
    hooks:
      - id: pyupgrade
        args: [ --py36-plus ]

  - repo: https://github.com/MarcoGorelli/auto-walrus
    rev: v0.2.2
    hooks:
      - id: auto-walrus

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: "v1.10.0"
    hooks:
      - id: python-check-blanket-type-ignore
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
        types: [ python ]
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-ast
      - id: check-docstring-first
      - id: check-executables-have-shebangs
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        args: [
          "--config=.flake8",
        ]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: venv/bin/pylint
        files: src
        language: system
        types: [ python ]
        args:
          [
            "--rcfile=.pylintrc",
            "-rn",
            "-sn",
          ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.3.0'
    hooks:
      - id: mypy
        args: [ --config-file=.mypy.ini ]
        additional_dependencies:
          - types-requests
