name: generate_docs
on:
  push:
    branches:
      - master
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - run: pip install mkdocs-material mkdocs mkdocstrings mkdocs-git-revision-date-localized-plugin mkdocs-git-committers-plugin-2 mkdocs-gen-files mkdocs-literate-nav mkdocs-section-index mkdocstrings-python mkdocs-autorefs
      - run: mkdocs gh-deploy --force --clean --verbose